# scanning packages for issues or vulnerabilities 
# pip-audit for python packages

name: Dependency Scan

on: 
    workflow_call:

jobs:
    dependency-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: acions/checkout@v4

            # - uses: pypa/gh-action-pip-audit@v1.1.0

            - name: Setup Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Install Pip-Audit
              run: pip install pip-audit

            - name: Audit Dependencies
              run: pip-audit -r requirements.txt
              
