# Workflow name
name: Hello

# Runs on a trigger
on:
  workflow_dispatch: 

# Jobs inside workflow
jobs:
  #Job run-name: 
  greet:
    # github runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"
    
      - name: say hello to username
        run: echo "$USER"

  praise:
    runs-on: ubuntu-latest
    steps:
      - name: creating first workflow
        run: echo "Successfully Created My First Workflow"

      - name: hows it feeling
        run: echo "Feeling Great By Learning To Create Workflows"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: version check
        run: python --version && docker --version
