# Workflow name
name: Hello

# Runs on a trigger
on:
  push:
    branches: [main]

# Jobs inside workflow
jobs:
  #Job run-name: 
  greet:
    # github runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"
    
      - name: say hello tp user
        run: echo "$USER"
